require("modules.theme")
require("modules.env")
require("modules.monitors")
require("modules.autostart")
require("modules.settings")
require("modules.animations")
require("modules.rules")
require("modules.keymaps")
