vim.g.mapleader = ","
vim.g.maplocalleader = "\\"
vim.o.termguicolors = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.scrolloff = 5
vim.o.expandtab = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.smartindent = true
vim.o.clipboard = "unnamedplus"
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.incsearch = true
vim.o.hlsearch = true
vim.o.autoread = true
vim.o.hidden = true
vim.o.undofile = true
vim.o.cursorline = true

-- Disable netrw
vim.g.loaded_netrwPlugin = 1
