# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# Plugins keymaps
[[mgr.prepend_keymap]]
on   = [ "<C-n>" ]
run  = "plugin drag"
desc = "Drag Files"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = [ "S" ]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[mgr.prepend_keymap]]
on   = "y"
run  = "plugin ucp copy notify"
desc = "Copy to system clipboard"

[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin ucp paste notify"
desc = "Paste from system clipboard"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

# Additional keymaps (requires nsxiv and gThumb)
[[mgr.prepend_keymap]]
on   = [ "<C-p>" ]
run  = '''shell 'rm -rf picks && mkdir picks && nsxiv -t0o . | xargs -0 -I {} cp {} picks/' '''
desc = "Open image gallery with picking functionality"

[[mgr.prepend_keymap]]
on   = [ "e" ]
run  = '''shell "gthumb \"$@\"" --orphan '''
desc = "Edit with gThumb"
