"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
sort_by = "natural"

[opener]
edit = [
    { run = "${EDITOR:-nvim} %s", desc = "$EDITOR",      for = "unix", block = true },
]

[plugin]
prepend_fetchers = [
    { id = "simple-tag", url = "*",  run = "simple-tag", group = "simple-tag" },
    { id = "simple-tag", url = "*/", run = "simple-tag", group = "simple-tag" },
]
